// Builds generated files in docs/:
//
// 1. docs/scriptable/IgnireCalendar.js: the Scriptable widget with the
//    calendar engine embedded, so users can paste one self-contained file.
// 2. docs/scriptable/source.js: the same text as a script for the website's
//    copy button (fetch() fails when the page is opened via file://).
// 3. Cache busting: every local asset URL in the HTML pages gets ?v=<content
//    hash>, and the pages and docs/version.json get a site version that
//    docs/update.js compares to load new deploys despite GitHub Pages' caching.
//
//   node scripts/build.mjs           write the files
//   node scripts/build.mjs --check   fail if any generated file is out of date

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const WEB_URL = "https://maplexgitx0302.github.io/Ignire_Bar/";
export const PAGES = ["index.html", "handbook.html"];

const root = new URL("../", import.meta.url);
const pathOf = (path) => fileURLToPath(new URL(path, root));
const read = (path) => readFileSync(pathOf(path), "utf8");
const hash = (content) => createHash("sha256").update(content).digest("hex").slice(0, 10);

export function buildScriptable() {
  return read("scripts/scriptable-widget.js")
    .replace("/*@@IGNIRE_CORE@@*/", () => read("docs/ignire-calendar.js").trimEnd())
    .replace("@@WEB_URL@@", WEB_URL);
}

export function buildSourceModule(script = buildScriptable()) {
  return (
    "// Generated by scripts/build.mjs: the Scriptable script as a string.\n" +
    `window.IgnireScriptableSource = ${JSON.stringify(script)};\n`
  );
}

// Local src/href values such as "style.css" or "scriptable/source.js?v=abc".
const ASSET_REF = /\b(src|href)="((?!https?:|\/\/|#|mailto:)[^"?]+\.(?:css|js|png|jpe?g|svg))(?:\?v=[0-9a-f]+)?"/g;
const VERSION_META = /<meta name="site-version" content="[0-9a-f]*">/;

/** Returns {path: content} for every generated file, given generated asset contents. */
export function buildSite(generated) {
  const assetContent = (path) =>
    generated[`docs/${path}`] ?? readFileSync(pathOf(`docs/${path}`));
  const outputs = { ...generated };
  const pageVersions = [];
  for (const page of PAGES) {
    const stamped = read(`docs/${page}`).replace(
      ASSET_REF,
      (_, attribute, path) => `${attribute}="${path}?v=${hash(assetContent(path))}"`
    );
    if (!VERSION_META.test(stamped)) throw new Error(`docs/${page} has no site-version meta tag`);
    outputs[`docs/${page}`] = stamped;
    pageVersions.push(stamped.replace(VERSION_META, ""));
  }
  const version = hash(pageVersions.join("\n"));
  for (const page of PAGES) {
    outputs[`docs/${page}`] = outputs[`docs/${page}`].replace(
      VERSION_META,
      `<meta name="site-version" content="${version}">`
    );
  }
  outputs["docs/version.json"] = `${JSON.stringify({ version })}\n`;
  return outputs;
}

export function buildAll() {
  const script = buildScriptable();
  return buildSite({
    "docs/scriptable/IgnireCalendar.js": script,
    "docs/scriptable/source.js": buildSourceModule(script),
  });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  for (const [path, content] of Object.entries(buildAll())) {
    if (!check) {
      writeFileSync(pathOf(path), content);
    } else if (readFileSync(pathOf(path), "utf8") !== content) {
      console.error(`${path} is out of date; run npm run build`);
      process.exit(1);
    }
  }
}
